# Importing needed modules

In [1]:
import numpy as np
import pandas as pd
import re

# Examining the data frame for personality scores

In [2]:
perscore_df = pd.read_csv("personality_scores.csv" , delimiter = ";")
perscore_df.head()

,ID,Section 5 of 6 [I am always prepared.],Section 5 of 6 [I am easily disturbed.],Section 5 of 6 [I am exacting (demanding) in my work.],Section 5 of 6 [I am full of ideas.],Section 5 of 6 [I am interested in people.],Section 5 of 6 [I am not interested in abstract ideas.],Section 5 of 6 [I am not interested in other people's problems.],Section 5 of 6 [I am not really interested in others.],Section 5 of 6 [I am quick to understand things.],...,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,IPIP_HIGH_RISK
0,0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Checking data summary for personality score

In [3]:
perscore_df.describe()

,ID,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,IPIP_HIGH_RISK
count,1555.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,777.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,449.034149,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,388.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,777.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1165.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1554.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Checking Missing values in personality score

In [4]:
perscore_df.isnull().sum()

ID                                                           0
Section 5 of 6 [I am always prepared.]                       0
Section 5 of 6 [I am easily disturbed.]                      0
Section 5 of 6 [I am exacting (demanding) in my work.]       0
Section 5 of 6 [I am full of ideas.]                         0
                                                          ...
Unnamed: 65                                               1555
Unnamed: 66                                               1555
Unnamed: 67                                               1555
Unnamed: 68                                               1555
IPIP_HIGH_RISK                                            1555
Length: 70, dtype: int64

In [5]:
perscore_df.shape

(1555, 70)

# Checking data types

In [6]:
perscore_df.dtypes

ID                                                          int64
Section 5 of 6 [I am always prepared.]                     object
Section 5 of 6 [I am easily disturbed.]                    object
Section 5 of 6 [I am exacting (demanding) in my work.]     object
Section 5 of 6 [I am full of ideas.]                       object
                                                           ...
Unnamed: 65                                               float64
Unnamed: 66                                               float64
Unnamed: 67                                               float64
Unnamed: 68                                               float64
IPIP_HIGH_RISK                                            float64
Length: 70, dtype: object

# Checking for duplicates based on ID

In [7]:
#Checking the number of unique values
perscore_unique = perscore_df["ID"].nunique()
perscore_unique

1555

There are 1555 unique values in the ID meaning that there are no duplicates in the ID of the dataframe

# Removing duplicates in ID column

In [8]:
 new_df = perscore_df.drop_duplicates(subset 
                                      = ["ID"], keep = "first",
                                      inplace = False)

# Dropping unnecessary columns

In [9]:
#Deleting the Unnamed: columns because they all have missing values

for trait in new_df:
    if "Unnamed:" in trait:
        del new_df[trait]
    elif "IPIP_HIGH_RISK" in trait:
        del new_df[trait]

# Renaming my dataframe to remove regular expressions

In [10]:
new_df.rename(columns = lambda x: x.replace('Section 5 of 6 [', ''), inplace = True)
new_df.rename(columns = lambda x: x.replace('.]',''), inplace = True)
new_df.rename(columns = lambda x: x.replace(']',''), inplace = True)
new_df.head()

,ID,I am always prepared,I am easily disturbed,I am exacting (demanding) in my work,I am full of ideas,I am interested in people,I am not interested in abstract ideas,I am not interested in other people's problems,I am not really interested in others,I am quick to understand things,...,I often forget to put things back in their proper place,I pay attention to details,I seldom feel blue (down),I spend time reflecting on things,I start conversations,I sympathize with others' feelings,I take time out for others,I talk to a lot of different people at parties,I use difficult words,I worry about things
0,0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,"(3, 5)","(3, 5)","(4, 3)","(5, 5)","(1, 3)","(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)"
1,1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)",...,"(3, 5)","(3, 1)","(4, 1)","(5, 5)","(1, 5)","(2, 5)","(2, 5)","(1, 5)","(5, 3)","(4, 3)"
2,2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,"(3, 5)","(3, 5)","(4, 1)","(5, 3)","(1, 3)","(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)"
3,3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)",...,"(3, 1)","(3, 5)","(4, 1)","(5, 5)","(1, 5)","(2, 5)","(2, 5)","(1, 5)","(5, 1)","(4, 1)"
4,4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)",...,"(3, 5)","(3, 5)","(4, 5)","(5, 5)","(1, 3)","(2, 3)","(2, 5)","(1, 3)","(5, 1)","(4, 3)"

In [11]:
new_df.shape

(1555, 51)

# Setting the ID column to be the index of the dataframe

In [12]:
per_in = new_df.set_index("ID")
per_in.head(5)

,I am always prepared,I am easily disturbed,I am exacting (demanding) in my work,I am full of ideas,I am interested in people,I am not interested in abstract ideas,I am not interested in other people's problems,I am not really interested in others,I am quick to understand things,I am quiet around strangers,...,I often forget to put things back in their proper place,I pay attention to details,I seldom feel blue (down),I spend time reflecting on things,I start conversations,I sympathize with others' feelings,I take time out for others,I talk to a lot of different people at parties,I use difficult words,I worry about things
ID,,,,,,,,,,,,,,,,,,,,,
0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)","(1, 3)",...,"(3, 5)","(3, 5)","(4, 3)","(5, 5)","(1, 3)","(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)"
1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)","(1, 3)",...,"(3, 5)","(3, 1)","(4, 1)","(5, 5)","(1, 5)","(2, 5)","(2, 5)","(1, 5)","(5, 3)","(4, 3)"
2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)","(1, 1)",...,"(3, 5)","(3, 5)","(4, 1)","(5, 3)","(1, 3)","(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)"
3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)","(1, 3)",...,"(3, 1)","(3, 5)","(4, 1)","(5, 5)","(1, 5)","(2, 5)","(2, 5)","(1, 5)","(5, 1)","(4, 1)"
4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)","(1, 1)",...,"(3, 5)","(3, 5)","(4, 5)","(5, 5)","(1, 3)","(2, 3)","(2, 5)","(1, 3)","(5, 1)","(4, 3)"

In [13]:
per_in.shape

(1555, 50)

# Checking is new data frame == original dataframe and asserting new data frame with original dataframe

In [14]:
if  len(perscore_df) == len( new_df ):
    print(True)
else:
    print(False)

True

In [15]:
assert len(perscore_df) == len( new_df )

# Importing departments dataframe

In [16]:
dep_df = pd.read_csv("departments.csv", delimiter = ";")

dep_df.head()

   ID Department
0   0       Data
1   1       Data
2   2       Data
3   3       Data
4   4       Data

# Checking the data summary for department

In [17]:
dep_df.describe()

                ID
count  1555.000000
mean    777.000000
std     449.034149
min       0.000000
25%     388.500000
50%     777.000000
75%    1165.500000
max    1554.000000

# Setting the ID column to be the index of the department dataframe

In [18]:
dep_ind = dep_df.set_index("ID")
dep_ind.head(5)

   Department
ID
0        Data
1        Data
2        Data
3        Data
4        Data

I have 5 major personality traits, and a number of sub-traits. Each sub-trait has a code indicating which major trait it belongs to.

For each row I have a number of columns. It looks as if each column apart from the ID column contains data for a sub-trait. The data is a 2-part tuple, where the first part is the code for the major trait, and the second part is the score for that particular sub-trait.
 So I will break down each tuple and work with it seperately.

# Looking at the first tuple in the dataframe

In [19]:
#subscale trait

def subscale(df):
    x = df.str[1]
    return x

In [20]:
#Creating a column to traits

sub_trait = per_in.apply(subscale, axis=1)
sub_trait= sub_trait.astype(int)
sub_trait.head()

,I am always prepared,I am easily disturbed,I am exacting (demanding) in my work,I am full of ideas,I am interested in people,I am not interested in abstract ideas,I am not interested in other people's problems,I am not really interested in others,I am quick to understand things,I am quiet around strangers,...,I often forget to put things back in their proper place,I pay attention to details,I seldom feel blue (down),I spend time reflecting on things,I start conversations,I sympathize with others' feelings,I take time out for others,I talk to a lot of different people at parties,I use difficult words,I worry about things
ID,,,,,,,,,,,,,,,,,,,,,
0,3,4,3,5,2,5,2,2,5,1,...,3,3,4,5,1,2,2,1,5,4
1,3,4,3,5,2,5,2,2,5,1,...,3,3,4,5,1,2,2,1,5,4
2,3,4,3,5,2,5,2,2,5,1,...,3,3,4,5,1,2,2,1,5,4
3,3,4,3,5,2,5,2,2,5,1,...,3,3,4,5,1,2,2,1,5,4
4,3,4,3,5,2,5,2,2,5,1,...,3,3,4,5,1,2,2,1,5,4

# Looking at the second tuple in the data frame

In [21]:
def major_t(df):
    x = df.str[4]
    return x

In [22]:
major_trait = per_in.apply(major_t, axis = 1)
major_trait = major_trait.astype(int)
major_trait.head()

,I am always prepared,I am easily disturbed,I am exacting (demanding) in my work,I am full of ideas,I am interested in people,I am not interested in abstract ideas,I am not interested in other people's problems,I am not really interested in others,I am quick to understand things,I am quiet around strangers,...,I often forget to put things back in their proper place,I pay attention to details,I seldom feel blue (down),I spend time reflecting on things,I start conversations,I sympathize with others' feelings,I take time out for others,I talk to a lot of different people at parties,I use difficult words,I worry about things
ID,,,,,,,,,,,,,,,,,,,,,
0,5,5,5,5,3,3,3,5,5,3,...,5,5,3,5,3,5,5,3,1,3
1,5,5,5,5,5,3,5,5,5,3,...,5,1,1,5,5,5,5,5,3,3
2,5,3,3,5,5,5,5,5,5,1,...,5,5,1,3,3,5,5,3,1,3
3,5,5,3,5,5,3,3,3,3,3,...,1,5,1,5,5,5,5,5,1,1
4,3,5,3,3,3,3,3,3,5,1,...,5,5,5,5,3,3,5,3,1,3

# Finding the sum of each subscale

In [23]:
traits = ["Extraversion","Agreeableness","Conscientiousness",
          "Neuroticism","Openness"]
subscores = pd.DataFrame()


def sum_subscale(sub, value):
    x = int(sub[1])
    y = int(sub[4])
    if (value == "Extraversion") and (x == 1):
        return y
    elif (value == "Agreeableness") and (x == 2):
        return y
    elif (value == "Conscientiousness") and (x == 3):
        return y
    elif (value == "Neuroticism") and (x == 4):
        return y
    elif (value == "Openness") and (x == 5):
        return y
    else:
        return 0



# Calculation total score

In [24]:
from functools import reduce
import operator

def subs_total(df, trait):
    person = []
    for a in range(len(df)):
        person.append(trait)
    subtot = list(map(sum_subscale, df, person))
    total = reduce(operator.add, subtot)
    return total

# Creating dataframe for subscales

In [25]:
for b in traits:
    indiv = []
    for a in range(len(per_in)):
        indiv.append(b)
    subscores[b] = list(map(subs_total, per_in.values, indiv))

# Creating a new merged dataframe

In [26]:
per_dep = pd.concat([dep_ind, new_df, subscores], axis = 1)
per_depi = per_dep.set_index("ID")
per_depi.head()

,Department,I am always prepared,I am easily disturbed,I am exacting (demanding) in my work,I am full of ideas,I am interested in people,I am not interested in abstract ideas,I am not interested in other people's problems,I am not really interested in others,I am quick to understand things,...,I sympathize with others' feelings,I take time out for others,I talk to a lot of different people at parties,I use difficult words,I worry about things,Extraversion,Agreeableness,Conscientiousness,Neuroticism,Openness
ID,,,,,,,,,,,,,,,,,,,,,
0,Data,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,"(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)",30,40,48,36,42
1,Data,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)",...,"(2, 5)","(2, 5)","(1, 5)","(5, 3)","(4, 3)",42,46,46,40,42
2,Data,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,"(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)",28,40,40,38,42
3,Data,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)",...,"(2, 5)","(2, 5)","(1, 5)","(5, 1)","(4, 1)",30,38,38,40,38
4,Data,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)",...,"(2, 3)","(2, 5)","(1, 3)","(5, 1)","(4, 3)",28,34,46,38,36

# Checking whether the number of rows in department dataframe == number of rows in merged dataframe

In [27]:
if  len(dep_ind) == len( per_dep):
    print(True)
else:
    print(False)

True

# Asserting that department dataframe == merged dataframe

In [28]:
assert len(dep_ind) == len(per_dep)

# Filtering merged dataframe

In [29]:
scored = 30
filtered_df = per_depi[(per_dep.Neuroticism < scored) & (per_dep.Conscientiousness < scored) & 
                      (per_dep.Agreeableness < scored)]
filtered_df

,Department,I am always prepared,I am easily disturbed,I am exacting (demanding) in my work,I am full of ideas,I am interested in people,I am not interested in abstract ideas,I am not interested in other people's problems,I am not really interested in others,I am quick to understand things,...,I sympathize with others' feelings,I take time out for others,I talk to a lot of different people at parties,I use difficult words,I worry about things,Extraversion,Agreeableness,Conscientiousness,Neuroticism,Openness
ID,,,,,,,,,,,,,,,,,,,,,
881,Data,"(3, 3)","(4, 1)","(3, 1)","(5, 5)","(2, 1)","(5, 3)","(2, 5)","(2, 3)","(5, 3)",...,"(2, 5)","(2, 3)","(1, 5)","(5, 1)","(4, 1)",30,28,26,28,36
1197,Copywriting,"(3, 5)","(4, 5)","(3, 1)","(5, 1)","(2, 1)","(5, 3)","(2, 5)","(2, 1)","(5, 1)",...,"(2, 5)","(2, 1)","(1, 3)","(5, 5)","(4, 1)",40,22,26,26,28

# Printing the ID numbers and departments of these applicants

In [30]:
print(filtered_df[["Department"]])

       Department
ID
881          Data
1197  Copywriting

# Assign these applicants as “high_risk” and “low_risk”

In [31]:
per_dep["Department"].value_counts()

Strategy       449
Data           329
Copywriting    326
Web Dev        170
Web dev        161
Design         120
Name: Department, dtype: int64

In [32]:
filtered_df["Department"].value_counts()

Data           1
Copywriting    1
Name: Department, dtype: int64

In [35]:
per_depi["Risk"] = np.where(
    (per_depi.Neuroticism < scored) & \
    (per_depi.Conscientiousness < scored) & (per_depi.Agreeableness < scored), 'High risk', 'Low risk'
)

# Creating a high and low risk column

In [36]:
risk_df = per_depi[["Department", "Risk"]].groupby(["Department", "Risk"]).size()
pd.DataFrame(risk_df)

                         0
Department  Risk
Copywriting High risk    1
            Low risk   325
Data        High risk    1
            Low risk   328
Design      Low risk   120
Strategy    Low risk   449
Web Dev     Low risk   170
Web dev     Low risk   161